### ISSUE TITLE
[1.17.1] Crash on world loading

### ISSUE THREAD

**Issue by ShinryuAspect** [TrattMods/LiterallyChunkLoader-1.15#11]
Hi, I'm getting a crash whenever y click the Play button on any world. Also, I don't think the reason behind this is running Optifine, as I've also experienced this crashwithout Optifine or any enhancement mods (such as Sodium or stuff like that).
I've also run a second test using the latest LibGui build from their GitHub and it also crashes under the same circumstances.
If you need me tu run any othe test so I can help you debug the problem, just say it.
Thank you in advanced.

[crash-2021-08-23_13.41.20-server.txt](https://github.com/TrattMods/LiterallyChunkLoader-1.15/files/7031561/crash-2021-08-23_13.41.20-server.txt)

**Comment by tratteo** [comment]
Are you running the correct version of Fabric API?

**Comment by ShinryuAspect** [comment]
I'm running the latest release available at Curseforge, which is 0.38.2. As it's stated in your mod's Curseforge page, requires 0.29+, so I assume using the latest is safe.

**Comment by tratteo** [comment]
This is a very weird crash, if you run only Fabric API and Literallychunk loader does it crash?

**Comment by ShinryuAspect** [comment]
I'm going to assume that it's not going to crash, as I've tested the Fabric API, LiterallyChunkLoader and ImmersivePortals alone and it didn't crash. Don't think that removing ImmersivePortals would make it crash.
It's probably a mod of the ones I'm running that causing and incompatibility, but it's so weird that it doesn't even let me in the world, I just click play and instant crash, the world didn't even have time to go through that "animated" loading screen (the one with a square that shows some chunks and features loading, Vanilla Minecraft thing).
I may run a few more tests later this afternoon to see if I can isolate the problems and I'll let you know if I come up with the mod crashing it. Also, could it be a datapack thing? I've several datapacks that alter the terrain generation and structures, but you never know with Java, it could also be the problem.

**Comment by tratteo** [comment]
As you can see i am getting the error in the mixin framework: 
`org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at Not Enough Crashes deobfuscated stack trace.(1.17.1+build.39)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:208)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178)
	at org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy.transformClassBytes(FabricMixinTransformerProxy.java:23)
	at net.fabricmc.loader.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:162)
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:154)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:519)
	at net.minecraft.server.world.ServerChunkManager.<init>(ServerChunkManager:87)
	at net.minecraft.server.world.ServerWorld.<init>(ServerWorld:200)
	at net.minecraft.server.MinecraftServer.createWorlds(MinecraftServer:383)
	at net.minecraft.server.MinecraftServer.loadWorld(MinecraftServer:350)
	at net.minecraft.server.integrated.IntegratedServer.setupServer(IntegratedServer:85)
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer:670)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer:270)
	at java.lang.Thread.run(Thread.java:831)
Caused by: org.spongepowered.asm.mixin.throwables.MixinError: Encountered undecorated Accessor method in lchunkloader.mixins.json:ThreadedAnvilChunkStorageInvoker applying to net.minecraft.class_3898
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.isAlreadyMerged(MixinApplicatorStandard.java:632)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.mergeMethod(MixinApplicatorStandard.java:548)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyAccessors(MixinApplicatorStandard.java:1054)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:393)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:320)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:345)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:569)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:351)
	... 14 more`
	
Taken alone like this the crash does not have much sense, since the mod alone works out just fine. It could be that some other mod is using mixin to alter the server tick manager in some way, or altering the `ThreadedAnvilChunkStorageInvoker` so that my mod is having problems on it. If you could run some tests and let me know what mod is causing the crash it would be fine. Then, we could see if the problem is actually a problem of mine concerning compatibility or a problem of the other mod.

**Comment by ShinryuAspect** [comment]
Sure, as I said, later this afternoon I'll try to go 1 by 1 (or in small groups) to see which one is causing it. I'm also going to assume that any of the QoL type mods (such as REI or stuff like that) can't cause the crash, but I may run a test with only those too if I can't seem to find the crash on any of the other ones.

**Comment by oBoLLl** [comment]
@tratteo I agree, the problems are similar at first glance. 8 hours of poking 1by1 mods showed that the crash was caused by the [SnowUnderTreesforFabric](https://www.curseforge.com/minecraft/mc-mods/snow-under-trees-fabric) . Why is this happening I do not understand. But removing it quite allows you to use the chunkloader.
